### ISSUE TITLE
DND .95 copmatability fixes

### ISSUE THREAD

**Issue by bsleys** [Moerill/Mess#102]
Upgrading to the DnD .95 version broke some stuff so far the one issue I've run across is below:

In dice.js the call is item._scaleCantripDamage the parameter order was changed. So change
``` javascript
item._scaleCantripDamage(newDmgPart, lvl, itemData.scaling.formula);
```
To:
```javascript
item._scaleCantripDamage(newDmgPart, itemData.scaling.formula, lvl);
```
If I run across any others I'll post them here

**Comment by Moerill** [comment]
done in one of the last patches, just forgot to close this issue...
