### ISSUE TITLE
Halfling Lucky trait not respected

### ISSUE THREAD

**Issue by DFreds** [Moerill/Mess#103]
![image](https://user-images.githubusercontent.com/11878569/90457976-0da32500-e0cb-11ea-97b6-30c8de6085db.png)

See image. 

When not using Mess, it uses the 1d20r=1 syntax for all rolls. Upon enabling Mess, this goes away and it stops rerolling 1s.

**Comment by Moerill** [comment]
This won't be fixed, only update for mess that will be coming (regarding rolling issues) is removing them.
My replacement is now submitted and waits for approval. Meanwhile you can download the module and look at its features from its repository:
https://github.com/Moerill/fvtt-mars-5e
Manifest: https://raw.githubusercontent.com/Moerill/fvtt-mars-5e/master/module.json
