### ISSUE TITLE
Broken Animated Tokens

### ISSUE THREAD

**Issue by JackaldaJester** [Moerill/Mess#104]
Module Version: 0.11.2
FVTT Version: 0.6.6
Browser: Chrome
OS: Windows 10

For my campaign I'm using animated tokens for my characters. When their cards show up in chat they appears as broken links. I don't think it would be possible to put a .webm file in chat, but would it be possible for the card to pull a tokens profile picture instead?

**Comment by Moerill** [comment]
This won't be fixed, only update for mess that will be coming (regarding rolling issues) is removing them.
My replacement is now submitted and waits for approval. Meanwhile you can download the module and look at its features from its repository:
https://github.com/Moerill/fvtt-mars-5e
Manifest: https://raw.githubusercontent.com/Moerill/fvtt-mars-5e/master/module.json
