### ISSUE TITLE
Cantrip damage scaling broken, cantrips stopped working.

### ISSUE THREAD

**Issue by Tronikart** [Moerill/Mess#105]
1. Module version
0.11.2
2. FVTT version
0.6.6
3. Browser and OS used. Or if the app itself is used.
Chrome 85.0.4183.83 Windows 10
4. Bug description 
    - What happened?
    Cantrip scaling is broken, if a PC higher than 5th level casts a cantrip, it won't work at all, not rolling the attack roll nor the damage, showing an error cursor when the "Attack" button is hovered.
    - What should've happened?
    Applied the correct scaling when needed (ie >5th-level PCs) and proceeded with the rest of the roll
    - Console errors? (F12 or F11 in most browsers)
```
entity.js:771 Uncaught (in promise) TypeError: scale.replace is not a function
    at Item5e._scaleCantripDamage (entity.js:771)
    at l (dice.js:314)
    at o (modify-rolling.js:160)
_scaleCantripDamage @ entity.js:771
l @ dice.js:314
o @ modify-rolling.js:160
async function (async)
o @ modify-rolling.js:159
r @ modify-rolling.js:89
_call @ foundry.js:2239
call @ foundry.js:2224
create @ foundry.js:9743
create @ foundry.js:28276
roll @ entity.js:314
async function (async)
roll @ entity.js:288
useSpell @ entity.js:618
_onItemRoll @ base.js:577
(anonymous) @ base.js:344
dispatch @ jquery.min.js:2
v.handle @ jquery.min.js:2
```
5. Workflow to recreate the bug
Have a spell with damage scaling set to "Cantrip" on a Character that's higher than 5th level and try to cast that spell with the Alternate Rolling and Targeting on
6. Helpful videos or screenshots if possible
Not sure if any of these would help but over on the Discord they mentioned how on the dnd5e system version 0.9.5 cantrip scaling broke and got fixed on 0.9.6, which may help.
7. Either activate notifications, stay active or post your discord handle so i can get back to you for further questions
wickedRobot#2069

**Comment by Moerill** [comment]
This also is fixed for some while now, just forgot to close it.
