### ISSUE TITLE
Template Grid never shows, no matter what options are selected

### ISSUE THREAD

**Issue by gravagehulk** [Moerill/Mess#110]
I had to stop using this module because my players had trouble telling where they were placing the template. I tried changing pretty much all of the options in the module, but none of them seem to make a difference. "Neither draw template borders..." is unchecked and that's the one I would specifically think would turn off the grid.

Am I missing something? Is there any way to show the template grid during placement like the default behavior without the module?

**Comment by Moerill** [comment]
ups this has been fixed for some while now.. forgot to close this issue
