### ISSUE TITLE
Damage Roll Chat Cards not working

### ISSUE THREAD

**Issue by kenpoh01** [Moerill/Mess#111]
Hello,

Just tried Foundry today, updated to 0.7 the other day.  Was trying some combat and noticed that the damage roll chat cards weren't working.  All I would get is a Card with the description of the attack and the attack button, but the attack button wouldn't work.  You could click on it, but it would just grey out without any other chat message popping up.  Turning off MESS seemed to fix the problem.  Wondering if there's a fix on the way or if someone knows if it's another module that's in conflict.
![MessError](https://user-images.githubusercontent.com/36082436/97786484-4018d600-1b82-11eb-8f1d-21f4b1ad3586.JPG)

**Comment by 00Muttley** [comment]
I have been having issues with this too. It's not a module compatibility thing as I deactivated all other modules and still had problems. If I deactivate the alternative rolling and targeting within MESS, I dont have any issues with attack/damage rolls and it works again.

**Comment by Moerill** [comment]
See here: https://github.com/Moerill/Mess/issues/109

FVTT 0.7.5 compatibility will still need some time and most stuff will be split into separate modules.

**Comment by Moerill** [comment]
must stuff i found should be fixed now, closing this for now..
