### ISSUE TITLE
Question about attack chat format. (dnd 5e)

### ISSUE THREAD

**Issue by Nedrapter** [Moerill/Mess#113]
Hello, I'm trying to make my rolls (for attack or damage) invisible to the players (so they won't know what kind of modifier the NPCs have) but allow them to see the result (without again checking what the result is made of ). Is this possible? If yes what combination of settings does it need?

**Comment by Moerill** [comment]
its the default (and currently only) way, that players can only see the total of the GMs rolls.

**Comment by Nedrapter** [comment]
The player is still able to see the dice rolled from the Dice so Nice module that shows "physical" dice being rolled. Any way to work around it, without completely disabling it?

**Comment by Nedrapter** [comment]
So after playing around a bit, I can get this done by selecting Public Roll before the attack, having all visible to players, then before clicking the Hit/Damage rolls, I switch to GM Roll. I can see this getting tedious quite fast though. Could it be automated?

**Comment by Moerill** [comment]
https://github.com/Moerill/Mess#always-show-gm-attack-card-to-players-but-rolls-only-on-demand

if you set that setting and set roll-mode to gm only, it should already be "correct" i think.

**Comment by Nedrapter** [comment]
Yeap it does! Thank you!
