### ISSUE TITLE
Rolling Attack and Damage not working

### ISSUE THREAD

**Issue by alcobeard** [Moerill/Mess#116]
Uncaught (in promise) TypeError: r._handleResourceConsumption is not a function at o (modify-rolling.js:191)

```
for (const target of targets) {
		const allowed = await item._handleResourceConsumption({ isCard: false, isAttack: true });
		const targetActor = target.actor ? target.actor.data : null;
```

Little addition - FVTT 0.7.8

P.S. Problem related to new release of dnd5e system 1.2.0. Roll back to previous version make problem disappeared

**Comment by alcobeard** [comment]
Little addition - fancy form doesn't work at all.
Foundry version 0.7.8.

**Comment by Moerill** [comment]
This won't be fixed, only update for mess that will be coming (regarding rolling issues) is removing them.
My replacement is now submitted and waits for approval. Meanwhile you can download the module and look at its features from its repository:
https://github.com/Moerill/fvtt-mars-5e
Manifest: https://raw.githubusercontent.com/Moerill/fvtt-mars-5e/master/module.json
