### ISSUE TITLE
Apply damage to tokens not working

### ISSUE THREAD

**Issue by ultrakorne** [Moerill/Mess#14]
Mess: v0.2
Foundry: v0.57, dnd5e v0.90, native client

Right clicking on the card and clicking apply damage with a selected token doesnt work as expected (tried with a creature with 100+ hp and the screenshot below and it killed the creature in 1 shot)

Would be cool to have it work with both the right click option on the card (as shown below). if multiple damage options are available like for a versatile weapons the rolled damage is used.

Another option is by having 4 small buttons appear on the right side of the damage, once the damage is rolled. (i think minorQOL does something like that)

![image](https://user-images.githubusercontent.com/2083769/82224607-57da0600-9924-11ea-8187-fd76aba14cdc.png)

**Comment by Moerill** [comment]
Its currently just not really implemented. 
I've created an issue already for this and linked this comment to it. Further discussion in the other issue please (https://github.com/Moerill/Mess/issues/9)

Thanks for testing and your thoughts!
