### ISSUE TITLE
Crash attempting to cast a spell

### ISSUE THREAD

**Issue by ultrakorne** [Moerill/Mess#16]
mess v0.2
foundry 0.5.7, dnd 0.90, native client

steps:
1) import brutus from starting heros
2) drag fireball from srd spell compendium into brutus sheet
3) attempt to cast fireball

![image](https://user-images.githubusercontent.com/2083769/82229724-1a2cab80-992b-11ea-9ad3-c3d8f2245d58.png)

doing the same without mess does work as expected

**Comment by Moerill** [comment]
cannot reproduce, got an idea though what it happens and hopefully fixed it.
