### ISSUE TITLE
Players with permission "player" are not allowed to roll their own dice

### ISSUE THREAD

**Issue by Moerill** [Moerill/Mess#24]

**Comment by Xeteskian** [comment]
Hi, Noticed this has been closed - is it fixed?
I'm seeing a permission error when player try to roll their own dice.  Happy to help troubleshoot if needed

**Comment by Xeteskian** [comment]
Doh! Never mind - updated from 0.3.1 to 0.3.3 and it fixed the problem :D

**Comment by Moerill** [comment]
perfect!
just wanted to ask :D
