### ISSUE TITLE
Factor the automatic texture filling of dnd5e templates out of the modify-rolling code.

### ISSUE THREAD

**Issue by Moerill** [Moerill/Mess#25]

**Comment by FillGee** [comment]
I would be super appreciative if this could be done, I noticed this was the case when I was testing and came to report it only to see this. I want to use the the custom spell template pictures, but my group already uses minorQOL for rolls and so I dont need the modified rolling (and would love to disable it to avoid confusion/issues).

Thanks for all your work on this module though, theres some really neat features.
