### ISSUE TITLE
Sometimes module does not work after enabling it

### ISSUE THREAD

**Issue by ultrakorne** [Moerill/Mess#26]
-foundry 0.5.7, mess 0.3.3
-no other modules active, quite an empty world.

trying to roll attacks from one of the start heroes or from a NPC monster and I get the following error in console.

- disabling and re-enabling the mod fixes the issue
- when dis and re-enabling the module sometimes this error appears again

modify-rolling.js:119 Uncaught (in promise) TypeError: Cannot read property 'value' of null
    at r (modify-rolling.js:119)
    at d (modify-rolling.js:351)
    at modify-rolling.js:729
    at Function._call (foundry.js:2204)
    at Function.call (foundry.js:2189)
    at Function.create (foundry.js:9424)
    at Function.create (foundry.js:27641)
    at Item5e.roll (entity.js:289)

**Comment by btunnadine** [comment]
- Foundry 0.5.7
- MESS 0.3.3
- DnD5e 0.9

I'm also getting this issue. It only seems to happen on 0.5.7 and on the standalone app for me, refreshing after everything has loaded in usually re-enables it though (no need to switch it off & on). It seems that once it has loaded at least once it is fine after that, until the app is closed again.

It also doesn't load the autoroll & initiative toggle etc. in the chat bar, but there are no console errors until trying to roll from a character sheet. Auto targeting for spells, sorting and prepared spells all work though.

**Comment by Moerill** [comment]
thanks for the reports.
I noticed some strange behaviour regarding loading of the script for modifying the rolls as well and am not completly sure what the reason is.
But it seems that the server sometimes has a problem dynamically loading the code. I'll try to further investigate this, but this will propably take some time.

**Comment by Moerill** [comment]
Ok, my current way of fixing this is:
i moved the whole modify rolling code to be loaded and executed in the *ready* hook. Now the controls in the chat log do jump in in a not so beautiful way, but it  seems to have removed most issues i had with loading scripts.
This does need further observing though, so please report back after 0.4 drops if it still doesn't work.

**Comment by Moerill** [comment]
Ok this is annoying
I should just stop doing dynamic imports, since they just result into annoying race conditions and the performance gain propably isn#t even there. (Since most files still are rather small)

**Comment by Lazytron** [comment]
I am not seeing an error in console on .60 in chome, but roll section of sidebar does not consistently render (usually does not), which i suspect is also a loading race.

**Comment by rockshow888** [comment]
I can confirm that the module seems to randomly stop working (testing without any other module). I'm using .6 in both chrome and firefox

**Comment by Moerill** [comment]
I hopefully fixed this with 0.4. Please report back (or create a new issue) if this still persists
