### ISSUE TITLE
Roll with dis-advantage toggle improvements

### ISSUE THREAD

**Issue by ultrakorne** [Moerill/Mess#27]
I like the icons approach for the normal, adv, dis roll compared to having the button toggles

two improvements i would suggest:

- the saturation of the disadvantage roll is not enough, the green dice is too visible and it almost looks like 1 green and 1 red dice at the same time. I would make the green way more faded out.

- allow right click to cycle in other direction. from normal roll with a left click you go to the disadvantage icon, with a right click you go do the advantage click. This way you are always 1 click away from your desired roll type.

**Comment by Moerill** [comment]
>  the saturation of the disadvantage roll is not enough, the green dice is too visible and it almost looks like 1 green and 1 red dice at the same time. I would make the green way more faded out.
I'm a bit confused by that one, since for me the green one feels barely visible - but i can try to improve contrast there a bit

second one is a good suggestion!
