### ISSUE TITLE
"Mess Template Texture Config for DnD Abilities" Not functioning (0.6.0)

### ISSUE THREAD

**Issue by dasuberchin** [Moerill/Mess#30]
The "Mess Template Texture Config for DnD Abilities" dialog is not able to be interacted with.  I am currently running Foundry 0.6.0 and 5e 0.91 on Firefox.

![image](https://user-images.githubusercontent.com/33440383/82700823-f7590a80-9c3c-11ea-99a0-d90e979c33bb.png)

Let me know if additional info is needed.

**Comment by MrPavao** [comment]
Same here with same versions on Chrome

**Comment by Lazytron** [comment]
Another confirmation on chrome

**Comment by Linksterz** [comment]
Same problem here
