### ISSUE TITLE
AoE saving throws and damage for spells do not roll when used in conjunction with MQOL

### ISSUE THREAD

**Issue by Avitale34** [Moerill/Mess#32]
As said in title, I noticed when using the module that AoE saving throws and damage for spells do not roll when used in conjunction with MQOL.

**Comment by Moerill** [comment]
https://github.com/Moerill/Mess#module-compatiblity

i know and i do not really care for mod compatibility. MQoL, betterrolls5e, ... all those are bound to clash with this one due to their inherent different structure and similarity in things they do.
