### ISSUE TITLE
One Token not rolling attacks

### ISSUE THREAD

**Issue by mdkrebs** [Moerill/Mess#33]
**Token Mold version**

.50

**FVTT version**

.60

**Browser and OS used. Or if the app itself is used.**

App

**Bug description**

**(a) What happened?**

For only one of the tokens, when you click on a Weapon to activate an attack, it puts into the chat window a button to attack but it does not actually attack or roll.

(b) What should've happened?

For every other token, when you click on a Weapon to activate an attack, it (1) automatically rolls the attack and (2) gives an option to click to roll for damage in the chat window

(c) Console errors? (F12 or F11 in most browsers)

Uncaught (in promise) ReferenceError: parts is not defined
    at l (dice.js:246)
    at r (modify-rolling.js:78)

**Workflow to recreate the bug**

Open Token sheet and click on a Weapon to attack.

**Helpful videos or screenshots if possible**

The first of 3 chat windows below demonstrates the issue with the problem token. The following two are what happens when any other token's weapon is clicked.

<img width="189" alt="Screen Shot 2020-05-28 at 8 48 26 AM" src="https://user-images.githubusercontent.com/6003139/83143467-010cc300-a0c0-11ea-8b04-5aa43e166d82.png">

**Either activate notifications, stay active or post your discord handle so i can get back to you for further question**

@squattypotty

**Comment by Moerill** [comment]
ups thanks thats propably just a small typo. will push a quick hotfix in a minute.
