### ISSUE TITLE
Cone Template Texture Scaling is Off (and a related feature suggestion)

### ISSUE THREAD

**Issue by Dumbhuman** [Moerill/Mess#37]
Textures being applied to the cone template are currently squished vertically, even if the image source being used is a square, so there is some repeating of the texture which occurs on the top and bottom of the wide end (most easily seen when using flat cones).  In DND5e, cones are as wide at the end as they are long, so a 1:1 height/width ratio square should fill an entire cone.

Here's an image comparing the same image source (a Hypnotic Pattern square with a light border) being applied to a 15' Cone and a 15' Square template:
![image](https://user-images.githubusercontent.com/63615591/83510258-8ce86b80-a481-11ea-9a54-61844f70e326.png)
Notice the light border is barely visible in the square, but on the cone it clearly shows where the tiling of the texture happens at the top and bottom.

For the feature suggestion: it would be very nice to be able to set the border color and fill color of a template along with the texture.  Having transparent options for both colors would be even more amazing if at all possible.

**Comment by Moerill** [comment]
oooh good call on the squishing textures! thanks.
All templates i've tested with just have to much alpha padding on that side to notice :sweat_smile: 

Regarding your suggestion:
* Fill color: what exactly do you mean with that? adding a tint to the texture?
* border-color: It's possible. i'll *maybe* add this. (its more of an: i don't want to do the UI thing than an implementation problem)

**Comment by Moerill** [comment]
For future suggestions/bug reports: please split the issue into 2. One for the bug report, one for the suggestion(s).

**Comment by Dumbhuman** [comment]
Sorry about that.  I'll split the suggestion in the future.  

As far as Fill color goes, it's used to highlight the grid system for targets if it's enabled so it often spills out beyond where the texture would be.  I've changed it to green for the cone in the below screenshot (it was purple in original screenshot):
![image](https://user-images.githubusercontent.com/63615591/83511715-ef426b80-a483-11ea-8f49-7d5d39f6309d.png)
Because the template textures have some transparency, the fill color underneath is detectable which is why a transparent option for that would make me very happy, but failing that, having fire spells automatically get a yellow border and orange fill while a cold spell automatically gets a white border and a blue fill would be great.  

Currently there's no way to turn off the fill color unless you turn off the grid for the map.

**Comment by Moerill** [comment]
Regarding the fill:
thats base FVTT behaviour for showing which squares are "hit" by a template and the color does represent the players color, to recognize the player who created the template.
Main reason for me to use templates is to have the "hit squares" marked and without the player coloring its to much work to notice which template is whoms. So i won't put that in here. (but if you want to have it, should be rather easy to implement as its own module)

This is also the reason why the texture has an opacity of around 0.8 (i think), so the marked grid below is noticeable.

**Comment by Moerill** [comment]
the wrong scaling though is fixed now!

**Comment by Dumbhuman** [comment]
Glad to hear the scaling is fixed.  Many thanks for that!

Personally, while I like the auto-targeting possibilities of the templates, I really dislike the automatically-assigned aesthetics which is why I'd be perfectly happy if they were transparent (and if the texture had no opacity setting other than that baked into the image).  I draw my own spell effects and having those carefully-crafted effects take on various underlying colors based on who placed them might just end up irking me enough to learn Javascript and write my own module for that (but more likely I'll be lazy and learn to play without my beloved grid).  I thought further template customization might fit in well thematically with what MESS already accomplishes (all of which is very great so thanks again) which is why I suggested it here, but I understand your reasoning for preferring the default behavior.

**Comment by Moerill** [comment]
i actually forgot the autotargetting, which makes the "what squares are covered" less useful.

i've created an issue with thoughts on how i could tackle this at least partially:
https://github.com/Moerill/Mess/issues/49
