### ISSUE TITLE
Jack of all Trades (5e) seems to prevent ability checks

### ISSUE THREAD

**Issue by Lazytron** [Moerill/Mess#39]
0.6 core, .92 5e, .52 MESS

![image](https://user-images.githubusercontent.com/32400728/83562204-c69b8f80-a4de-11ea-8624-539e83486914.png)

Saves, skill checks are OK, but basic stat checks error out ONLY when JoAT is enabled.

**Comment by Moerill** [comment]
is fixed with 0.6.0
