### ISSUE TITLE
Modifiers applied in the special trait menu breaks MOSS attack card

### ISSUE THREAD

**Issue by Howll88** [Moerill/Mess#45]
If you set for example +2 from Archery Fighting Style in the special trait menu on the character sheet the MOSS attack card does not function. Workaround for now is to simply set it on the item for players that need such modifiers.

**Comment by Moerill** [comment]
https://github.com/Moerill/Mess#bug-reporting

**Comment by bsleys** [comment]
I think the problem is the +.  Just enter "2" without the plus.

Bob

**Comment by Howll88** [comment]
Yep, that was the issue bsleys, cheers
