### ISSUE TITLE
A way to handle bonus damage

### ISSUE THREAD

**Issue by bsleys** [Moerill/Mess#46]
I've haven't found a way to handle "bonus" damage from sneak attacks, hex etc that I liked.  When clicking damage rolls a popup shows in the unmodified Foundry to add bonuses etc.  Manually entering in the popup or doing a separate attack for it just feels like extra work and clunky.

So I decided to try to add it to mess in a way that seems reasonable to me, IE similar to how versatile damage is done.  What I added was a check box to items/spells etc to flag them as a bonus damage item and then when an attack is done their damage is added to the attack card just like versatile damage is for weapons.  See below for example of a rogue/warlock with sneak attack and hex.  The downside is the damage list can get long but I figure most chars aren't going to have a bunch of possible bonus damages like this.

![mess-damage](https://user-images.githubusercontent.com/105347/84404403-c2edc400-abd4-11ea-9167-4e40fed95355.png)

Let me know what you think and if interested I'll of course pass on the code.

Bob

**Comment by Moerill** [comment]
Heya, nice idea!

but i'm not completly sure about it. The way we are doing it is by having feature bonuses just being "used" seperately or toggled via a macro. Which is.. okayish?

Could you maybe send me the code and i'll play around with it a bit, to see how it feels?
Thanks anyway already!

**Comment by bsleys** [comment]
I'll put together a pull request for you tomorrow, or if you prefer I can
post the code...not too many changes, think just 2 files.


Bob

**Comment by bsleys** [comment]
Bah waiting my turn in a game so here's the code :P.

in modify-templates.js I updated itemHook to add the checkbox to items/spells etc.
```javascript
async function itemHook(app, html) {
	var div = document.createElement('div');
	div.classList.add('form-group');
	div.appendChild(document.createElement('label')).innerText = 'Template Texture';
	var formField = div.appendChild(document.createElement('div'));
	formField.classList.add('form-fields');
	var inp = formField.appendChild(document.createElement('input'));
	inp.dataset.dtype = 'String';
	inp.type = 'text';
	inp.name = 'flags.mess.templateTexture';
	inp.value = app.object.getFlag('mess', 'templateTexture') || "";

	formField.insertAdjacentHTML('beforeend', `
		<button type="button" class="file-picker" data-type="imagevideo" data-target="flags.mess.templateTexture" title="Browse Files" tabindex="-1">
			<i class="fas fa-file-import fa-fw"></i>
		</button>
	`);
	const button = formField.querySelector('button');
	button.style.flex = '0';
	app._activateFilePicker(button);
	var target = html[0].querySelector('[name="data.target.units"]');
	if (target)
		target.closest('.form-group').after(div);


	div = document.createElement('div');
	div.classList.add('form-group');
	div.appendChild(document.createElement('label')).innerText = 'Bonus Damage Ability';
	formField = div.appendChild(document.createElement('div'));
	formField.classList.add('form-fields');
	inp = formField.appendChild(document.createElement('input'));
	inp.type = 'checkbox';
	inp.name = 'flags.mess.isBonusDamage';
	inp.checked = app.object.getFlag('mess', 'isBonusDamage');

	target = html[0].querySelector('[name="data.formula"]');
	if (target)
		target.closest('.form-group').after(div);
}
```
Then in dice.js  in getDmgData just below 
```javascript
	if (itemData.damage.versatile) 
		rollData.parts.splice(1, 0, [itemData.damage.versatile, "versatile"]);
```
add the following
```javascript
	for (let itm of actor.items){
		let bnsDmgParts = [];
		if (itm.getFlag('mess', 'isBonusDamage')){
			if (itm.hasDamage){
				const itmData = itm.data.data;
				bnsDmgParts.push(itmData.damage.parts[0][0]);
				var lbl = itm.name;
				if (itmData.damage.parts[0][1].length > 0) lbl += ` - ${itmData.damage.parts[0][1]}`;
				bnsDmgParts.push(lbl);
			}
		}
		if (bnsDmgParts.length > 0) rollData.parts.push(bnsDmgParts);
	}
```
I think that covers it.

Bob

**Comment by Moerill** [comment]
perfect, thanks!

i almost entirely absorbed it, with only small tweaks.
* Put the  itemhook into its own hook, so its activated by the modifying rolls settings
* Added a small check so an item adding bonus dmg does not get bonus dmg from other items. (e.g. if you want to roll sneak attack allone)
* Added a small macro to quickly toggle the status for an item

**Comment by Moerill** [comment]
by the way @bsleys how do you want to get attributed in the changelogs?
Using your github name "bsleys", your real (?) name "bob sleys", shown in your github profile, or a discord tag (don't know that one)?

**Comment by bsleys** [comment]
discord tag is Thirsterhall@2424

As for credit it doesn't matter to me. I'm not concerned with credit.  If I can be of some help that's enough for me.

**Comment by Moerill** [comment]
Thats nice of you! Buuut imo credit is due where credit is due!
