### ISSUE TITLE
Damage formulas not working 100% currectly

### ISSUE THREAD

**Issue by bsleys** [Moerill/Mess#48]
Found a problem with using data formulas for example for rogue sneak attacks "ceil(@classes.rogue.levels/2))d6" would display the full formula and if its a crit hit both my new code based on Roll.alter() and Roll.alter can't handle the formula.  To clean up the display in the damage card and make crits work correctly at the bottom of getDmgData in dice.js where it looks like you are handling localizations of damage types change the loop per below to also evaluate the formula

```javascript
	for (let part of rollData.parts) {
		let roll = new Roll(part[0], rollData);
		const dmgType = CONFIG.DND5E.damageTypes[part[1]];
		if (dmgType)
			part[1] = game.i18n.localize('DND5E.Damage' + CONFIG.DND5E.damageTypes[part[1]]);
		else if (part[1] === 'versatile')
			part[1] = game.i18n.localize('DND5E.Versatile');

		//evalute damage formula's for example "ceil(@classes.rogue.levels/2))d6" -> "4d6"
		let terms = roll._evalParentheticalTerms(roll.formula).map(t => {
			if ( t instanceof Roll ) {
				t.roll();
				return t.total;
			}
			return t;
		});
		part.push(terms.join(''));
	}
```

**Comment by Moerill** [comment]
oh nice catch,  thanks!

i actually knew that wouldn't work, but accepted it due to ```roll.alter```(used e.g. in the base 5e system) not being able to work with it as well :grimacing: 
But that is a nice solution to the problem until FVTT v0.7.0 arrives and solves the problem in core. :sweat_smile:
