### ISSUE TITLE
Chat Card GM Helpers

### ISSUE THREAD

**Issue by Moerill** [Moerill/Mess#52]
Add some actions/views to chat cards, for GM only:
* show target AC/HP
* roll saving throws for all (non character) targets for a saving throw spell (Think about auto applying dmg? Propably not.. but .. hmmm)

Testing a few of those things using overlays on hover.

Also use css classes to hide the information from players. (yes they could go into console and change that stuff.. but cheating is already easy in FVTT, so why make it more complicated? :shrug:

**Comment by Moerill** [comment]
first version just includes showing ac of the target for gm only.
![image](https://user-images.githubusercontent.com/26152015/85406075-8c636200-b561-11ea-94fc-abebeaa28b68.png)

**Comment by Moerill** [comment]
Change in Idea here:
- always show target (and attacker)  to players (if not gm only roll) but hide rolls
- allow GM to display (i think dmg only) rolls (automatically), when rolled, to players, without extra information like amount of dice used, modifier, ....
- *maybe* show "hit" / "miss" for attack rolls and allow to show that information (automatically) to the players.

**Comment by Moerill** [comment]
Added damage resistances, vulnerabilities and immunities to the overlay:
![image](https://user-images.githubusercontent.com/26152015/86024635-866ff400-ba2d-11ea-9cd5-dd2b60dbda14.png)

**Comment by Moerill** [comment]
![image](https://user-images.githubusercontent.com/26152015/86024780-b5866580-ba2d-11ea-96e5-35a71140b154.png)
GM Rolls now have a unique style:
GMs can roll openly, to just display the attacker and weapon used and show the target.
Then for either hits or dmg dice they can decide to show the final rolled results by clicking on the eye icon. (rolled only) Players then are able to see those results, but not the components (or rolled dice results)

**Comment by bsleys** [comment]
Looking nice.

Did you add in the custom DI/DR stuff?  I had a bit of a time with it.

Now it just needs to handle multiple targets for AOE stuff LOL.  Ya I know that's going to make the target area even more crowded.  Not only would multiple target icons need to be displayed but also a way for the DM to select which targets to apply the damage too since different targets can have different DI/DR etc.  Perhaps a checkbox on/next to each target image?

Bob

**Comment by Moerill** [comment]
> Did you add in the custom DI/DR stuff? I had a bit of a time with it.
yes

> Now it just needs to handle multiple targets for AOE
hm.. won't make that for the time being
not sure as to how i want to handle this without spamming to much (e.g. fireball on 10 means chatlog overload)

**Comment by Moerill** [comment]
> ![image](https://user-images.githubusercontent.com/26152015/86024780-b5866580-ba2d-11ea-96e5-35a71140b154.png)
> GM Rolls now have a unique style:
> GMs can roll openly, to just display the attacker and weapon used and show the target.
> Then for either hits or dmg dice they can decide to show the final rolled results by clicking on the eye icon. (rolled only) Players then are able to see those results, but not the components (or rolled dice results)

Stuff to consider:
currently for this you'd have to roll public. This means that either the GM has to switch roll modes all the time or players do see everything.
options here:
a) override roll type for attack cards (let setting decide whether this is enabled or not)
b) add extra button to attack cards to easily show them

**Comment by bsleys** [comment]
> hm.. won't make that for the time being
> not sure as to how i want to handle this without spamming to much (e.g. fireball on 10 means chatlog overload)

Ya not going to be easy to make it look decent.  I was thinking more of 1 attack card with 10 target images with ability to roll saves, via context menu on image OR way to select multiple images and trigger saves/apply damage.

> a) override roll type for attack cards (let setting decide whether this is enabled or not)
> b) add extra button to attack cards to easily show the

Personal opinion here is a setting in MESS config that determines visibility of the rolls.  That way its a one time set and forget vs constantly changing and always forgetting and exposing rolls I didn't want seen LOL, I know I'd screw that up way to many times LOL.

Bob

**Comment by bsleys** [comment]
Just thought of another detail that would be handy for a DM.  Range to target and weapon/spell range to help determin if the attack roll should be with disadvantage or not.  Perhaps adding the weapon short/long range to the weapon description say something like Shortbow (80/320) and on the target someplace display the range to the target.  Getting the range can be tricky so here's a function that does the trick.

``` javascript
function getDistance (t1, t2, wallblocking = false) {
		var x, x1, y, y1, d, r, segments=[], rdistance, distance;
		for (x = 0; x < t1.data.width; x++) {
			for (y = 0; y < t1.data.height; y++) {
		   		const origin = new PIXI.Point(...canvas.grid.getCenter(t1.data.x + (canvas.dimensions.size * x), t1.data.y + (canvas.dimensions.size * y)));
		    	for (x1 = 0; x1 < t2.data.width; x1++) {
		      		for (y1 = 0; y1 < t2.data.height; y1++){
				   		const dest = new PIXI.Point(...canvas.grid.getCenter(t2.data.x + (canvas.dimensions.size * x1), t2.data.y + (canvas.dimensions.size * y1)));
				   		const r = new Ray(origin, dest)
				   		if (wallblocking && canvas.walls.checkCollision(r)) {
				   			continue;
				   		}
				   		segments.push({ray: r});
		    		}
				}
			}
		}
		if (segments.length == 0) {
			return -1;
		}
		rdistance = canvas.grid.measureDistances(segments, {gridSpaces:true});
		distance = rdistance[0];
		rdistance.forEach(d=> {if (d < distance) distance = d;});
		return distance;		
	};
```
Note the above can also take into account wall blocking and if set and the target has full cover the range is returned as -1.

Bob

**Comment by Moerill** [comment]
thanks
but i'm a little bit torn  on this.
On one hand i see the appeal, having a number there and not measure yourself
on the other hand imo the players should do at least some things themself.. and this is one.
(Also i find measuring kinda fun and an important part. Possibly due to my infinity and warhammer 40k past..)

i'll  think about it, maybe include it. But i wouldn#t want the wall blocking part for one main reason: performance. There is already a small delay when clicking a button and checking wall blocking (for each target) just  increases this to much  imo

**Comment by Moerill** [comment]
Ok i thought of a reason against the range measurement:
you'd always have to make sure to use the action from the proper token. (Which i actually a lmost never do)
and for those cases when you do not its  "just" confusing.

**Comment by Moerill** [comment]
i'll keep it in the current state (ac, dr, di, dv displayed) for this version
and maybe reiterate over it later on.
