### ISSUE TITLE
Animated templates not working

### ISSUE THREAD

**Issue by oathbounddnd** [Moerill/Mess#54]
Module Version: 0.8.0
FVTT Version: 0.6.2
App used
When placing templates, animated ones of any file type do not work. They either appear as a still image or do not appear at all. The option for "Neither draw template borders nor highlight grid..." can be turned off, but doesn't effect the game at all, as in, it still functions as though it was left on. Removed all modules to test if that was the issue, but it persisted
![screen-recorder-video-2020-15-6](https://user-images.githubusercontent.com/47308890/84677591-d7a8bf80-af26-11ea-864d-fd54f3a36275.gif)

Discord: Aoife Tadgh#9201

**Comment by Moerill** [comment]
already fixed in v0.8.1
