### ISSUE TITLE
Combat sounds

### ISSUE THREAD

**Issue by bsleys** [Moerill/Mess#57]
Since Mess already does graphics for templates based on damage type the next logical step would be sounds.  Setup similar to graphics tmeplates only fumble, miss, hit and critical for each damage type with fallbacks from crit->hit and fumble->miss if nothing specified.  IE if no fumble slashing sounds is set the use miss slashing instead etc.

Of course if it's something you'd be interested in Mess having I'll take a shot it getting it working.

Bob

**Comment by Moerill** [comment]
doesn't [Maestro](https://github.com/death-save/maestro) do this already?
Would be better to maybe make them work together (if they don't, haven't tested) instead of reimplementing  it.
