### ISSUE TITLE
Can't move items into subfolders

### ISSUE THREAD

**Issue by bsleys** [Moerill/Mess#60]
When "Activate nicer drag animations for sidebar" is enabled items can be moved into folders and empty folders fine but you can move an item into an empty subfolder. If you create an item inside a sub-folder first so it's not empty then you can move things in fine you just move them into empty subfolders.

Hope that make sense.

Bob

**Comment by CarnivorousM** [comment]
Came to mention this also:
I have noticed similar (with and without the 'nicer drag' setting). I also have a similar issue dragging maps into folders. If I deactivate this module - it works again.
If I try to drag an Actor or Map into a folder (with things in it or not) - it 'bounces' back into the original folder to a random spot in the lineup.

**Comment by Moerill** [comment]
hmm parts of those bugs make me wonder..
need to do some testing.
May take a few days until i can fix  this.

**Comment by Khybersghost** [comment]
I've also noticed, at least with the PF2 system when using only this mod, it breaks the ability to drag items into inventory containers such as Bags etc

**Comment by Linith** [comment]
I am experiencing this issue as well. Unable to drag and drop items into folders.

**Comment by Moerill** [comment]
I think i've fixed it now.
Though for pf2e container it does look a little bit misleading.
And for scenes (especially without thumbnails) it does look a bit strange as well.
