### ISSUE TITLE
Possible rotation issue with cones

### ISSUE THREAD

**Issue by kandashi** [Moerill/Mess#62]
So using MESS and Animated Spell Effects, when I use the automated effect config menu the cone effects are always rotated 90 degrees compared to the template
![image](https://user-images.githubusercontent.com/1347785/85609654-34eef000-b64e-11ea-9798-a2a5c2fb063a.png)

**Comment by Moerill** [comment]
You need to use the "correct" cone there.  All are now rotated correct (to my knowledge), but on a quick check the red one has 2 versions, one rotated "wrong", one rotated correctly

**Comment by Moerill** [comment]
![image](https://user-images.githubusercontent.com/26152015/85610419-48528900-b657-11ea-9af0-6ccf9ab85879.png)
