### ISSUE TITLE
Add a checkbox on configuration for disable "Autoroll and Advantage toggle" feature

### ISSUE THREAD

**Issue by p4535992** [Moerill/Mess#64]
**Detail of the world:**

Foundry Virtual Tabletop, version 0.6.4
System Core: Dungeons and Dragons 5th Edition, version 0.92
Modules Installed: M.E.S.S. (Moerill’s Enhancing Super Suite) 0.9.0

**Description of the issue:**

Some of my players prefer the standard roll prompt of Foundry. 
it's possible to add a checkbox on the configuration of the module for disable the feature "Autoroll and Advantage toggle"?

**Comment by Moerill** [comment]
No, this is actually integrated to deep into the core module and to much work to remove.
