### ISSUE TITLE
Apply damage to target

### ISSUE THREAD

**Issue by bsleys** [Moerill/Mess#65]
Been messing around with the applying damage to the target of an attack.  Here's what I've come up with so far.  Note the look still needs work as my css skills aren't the best in the world but it's functional at lease.

Given this attack card the GM and only the GM can shift click the target image.
![mess-attack](https://user-images.githubusercontent.com/105347/86008786-44bc5a80-b9e7-11ea-807a-43d30796487f.png)

And the following dialog pops up.
![mess-apply-dmg](https://user-images.githubusercontent.com/105347/86008821-543ba380-b9e7-11ea-86a4-f9d0d383e635.png)

Simply click the buttons and save.

Note that only damage rolls that have been rolled show up to be applied (sneak attack can be applied since it wasn't rolled) and the GM still has full control on the which and how the damage is applied to the target. 

Bob

**Comment by Moerill** [comment]
oh thanks
but i've already implemented a method coming next update (soonish). Reasoning for context menu is that it somehow simulates default 5e behavior here. (and i kinda like it)
See this issue:
https://github.com/Moerill/Mess/issues/9#issuecomment-648100988

**Comment by bsleys** [comment]
Just saw that.

However how would you deal with someone that was resistant to force but not the slashing damage, using your example in #9?  The damage should be 18 (15 slashing + 3 force).

Bob

**Comment by Moerill** [comment]
My contextmenu does not care about dmg types or resistances.

In your specific case, just apply each die manually 
(right clicking die => only die dmg will get respected. right clicking the damage "header" => all rolled die together will get used in the dmg calculation.)

i do want to test my approach a bit in my games first. And possibly iterate on this.
(Writing this answer i am thinking of maybe combining your idea and mine... Since i'm not 100% happy with the versatile/non versatile solution. But i'm not sure here. First some testing.)

**Comment by bsleys** [comment]
Ya I see now..I glossed over the individual assignments.

How would you feel about buffing up the target area of the attack card?  IE
adding AC, DR, DI, DV somehow.  Perhaps only for the GM to serve as a quick
reminder to apply damage etc with out having to open the NPC/PC sheet.

**Comment by Moerill** [comment]
the DR, DI, DV part is actually a good idea!
the ac is already shown in my current version of the next update, but i couldn't think of more stuff to show there :facepalm: stupid me
![image](https://user-images.githubusercontent.com/26152015/86018268-64727380-ba25-11ea-85ca-c8447b3e1db9.png)

**Comment by Moerill** [comment]
do you have any idea for nice icons for those attributes? i'd prefer to use icons instead of text there

**Comment by Moerill** [comment]
cause.. oh damn t hats getting full fast:
![image](https://user-images.githubusercontent.com/26152015/86020616-6be74c00-ba28-11ea-8818-5dcf8f9fd690.png)

**Comment by Moerill** [comment]
ok found a solution (using icons) that i'm happy with:
![image](https://user-images.githubusercontent.com/26152015/86024635-866ff400-ba2d-11ea-9cd5-dd2b60dbda14.png)

**Comment by Moerill** [comment]
(Also moving further discussion for this on to https://github.com/Moerill/Mess/issues/52 )
