### ISSUE TITLE
Ability saves conflict with Tidy5e sheet

### ISSUE THREAD

**Issue by bsleys** [Moerill/Mess#66]
It looks like Mess at actorSheetHook in modify-rolling is making the ability mod and save bonus mods clickable to roll ability checks and saves respectively. However when using Tidy5e Sheet (https://github.com/sdenec/tidy5e-sheet) it has that built in so when doing a ability save via the modifier two saves are rolled on from MESS and one from Tidy5e.

Bob

**Comment by bsleys** [comment]
Interestingly only the saves gets double rolled.  For a check Mess code is overriding tidy5e and doing the roll directly and no popup (from tidy5e) to select adv/dis is shown but for the save both MESS's roll is done and tidy5e's displays the adv/dis popup.

Bob

**Comment by Moerill** [comment]
good timing on this bug report, just wanted to wrap up the release :sweat_smile: 
also interesting that neither me nor my players noticed this during our games.

**Comment by bsleys** [comment]
I prefer your way to roll directly and bypass the popup, thanks to the adv/dis button you have already.

**Comment by acd-jake** [comment]
It seems this is an issue in version 0.11 also. Affected are ability saves and skill rolls. 

Mike

**Comment by Moerill** [comment]
I can't reproduce this issue anymore. For me everything rolls as expected, on both the character and npc sheet.

Please make sure to disable *all* other mods beside tidy5e and MESS and try again.

**Comment by acd-jake** [comment]
Hello, sorry my fault... 

the incompatibility is not with tidy5e, but with "BetterRolls5e" (https://github.com/RedReign/FoundryVTT-BetterRolls5e/tree/master/betterrolls5e). Rolling a save or a skill creates a duplicate roll in the chat. One with the standard mechanism and one with betterrolls5e.
![image](https://user-images.githubusercontent.com/67855941/86558498-c79a6380-bf59-11ea-95a7-bd7fbb694707.png)

**Comment by Moerill** [comment]
thanks for checking and clarifying this.

that is a conflict i actually do not care about though. BetterRolls5e and MESS' alternative rolling are bound to conflict.
