### ISSUE TITLE
GM chard info icons missing

### ISSUE THREAD

**Issue by bsleys** [Moerill/Mess#72]
Is it just me or the ac, di etc info icons missing from the DM chat card?
Also wasn't the GM card styled dark?
![gm-card](https://user-images.githubusercontent.com/105347/86540315-32a05780-bed2-11ea-880b-48609b975b9e.png)
Bob

**Comment by Moerill** [comment]
the style is only cause the gm in the  video had dark mode activated while player not.

**Comment by Moerill** [comment]
as for your actual issue:
there is missing like.. all extra information!
error logs, etc.
Buuut i just noticed it  missing as well. Seems  like the build process failed to add the image files.
