### ISSUE TITLE
Ranged Spell Attacks not working

### ISSUE THREAD

**Issue by Ethmaker** [Moerill/Mess#78]
**Module Version:** Latest (0.11.2)
**Foundry Version:** Latest Stable (0.6.4)
**Browser/Os/App:** The Electrum app is used.
**What happened:** When clicking on a ranged spell, the attack box never shows but the info box of the spell does.
**What should've happened:** The attack box should also appear.
**Console Errors:**
![image](https://user-images.githubusercontent.com/42974296/86652363-f6d8c100-bfa9-11ea-8e69-87b8e34dacfc.png)
**Workflow to recreate:** Use a spell with a ranged attack in it.
**Discord Handle:** Ethmaker#5998 (I am open to DMs)

**Comment by Moerill** [comment]
This is something i can't observe myself for all spells i tested.

Make sure to disable _all_ other modules and test again.
If it still fails: Could you please give some details about the spells that make issues? Like a screenshot of the itemsheets.

**Comment by Moerill** [comment]
also interesting would be the special traits section of the character sheet you used for testing

**Comment by Ethmaker** [comment]
I just tried in a brand new world with only MESS installed and it still happens if you set the action as a Ranged Spell Attack
![image](https://user-images.githubusercontent.com/42974296/86656697-45d42580-bfad-11ea-900c-684c338e7f2c.png)

Since it's a brand new world and an unedited sheet with a custom spell added with only Ranged Spell Attack as a part of it and 1d8 damage, the special traits would be the Foundry Default

That leads me to believe it would be *all* spells of that sort

**Comment by Ethmaker** [comment]
![image](https://user-images.githubusercontent.com/42974296/86657104-951a5600-bfad-11ea-9944-2c36cb0587dc.png)
![image](https://user-images.githubusercontent.com/42974296/86657171-a3687200-bfad-11ea-98d7-593c2cbd1620.png)
![image](https://user-images.githubusercontent.com/42974296/86657200-a95e5300-bfad-11ea-9723-6ba7e2be3a26.png)

**Comment by Moerill** [comment]
> I just tried in a brand new world with only MESS installed and it still happens if you set the action as a Ranged Spell Attack
> ![image](https://user-images.githubusercontent.com/42974296/86656697-45d42580-bfad-11ea-900c-684c338e7f2c.png)
> 
> Since it's a brand new world and an unedited sheet with a custom spell added with only Ranged Spell Attack as a part of it and 1d8 damage, the special traits would be the Foundry Default
> 
> That leads me to believe it would be _all_ spells of that sort

This is actually a differnet error to your first one.
This one i know the reason of - its cause you don't have a scene active in a brand new world. (Though in real games this should almost never be a problem i propably should still fix it)

**Comment by Ethmaker** [comment]
Fair enough, that did fix the issue then, I'll go and test what exactly causes the spell to break then specifically

**Comment by Moerill** [comment]
thanks! (;

**Comment by Ethmaker** [comment]
Found out the reason, it was like you alluded to, the character sheet I ran into the issue with has a +2 Ranged Spell Attack modifier in Special Traits, I am using the Sky's Alternative Char Sheet module too

**Comment by Moerill** [comment]
is the exact value a "+2"? (just wanting to make sure i'll test the right thing. Also i'm kinda confused since that is supposed to work...)

**Comment by Ethmaker** [comment]
Yes, it is exactly that

**Comment by Moerill** [comment]
perfect, thank you for your effort! i can replicate that and will solve it for next patch

**Comment by Ethmaker** [comment]
Good to know!

**Comment by Moerill** [comment]
for the time being removing the "+" should work just fine as modifier

**Comment by Moerill** [comment]
note to myself: seems only to be a problem with spells. => Compare the differences between item and spell usage.

**Comment by Ethmaker** [comment]
The modifier does work like that, however when you do "2+2" in with Dynamic Effects, it has the dice roll show the first number but not the second when you see the modifiers, but it still adds it properly
