### ISSUE TITLE
Improper display of rolled dice

### ISSUE THREAD

**Issue by bsleys** [Moerill/Mess#83]
While working on #80 I found a bug in the tool tip, expanded view of rolled dice.
![crit display](https://user-images.githubusercontent.com/105347/87228162-4b46bc80-c36d-11ea-98db-4696fef17504.png)
In the above case the original formula was 1d6 + 2d6.  Since it was a crit hit it became 1d6 + 6 + 2d6 + 12.  And can see the result is a bit messed up.

**Comment by Moerill** [comment]
This won't be fixed, only update for mess that will be coming (regarding rolling issues) is removing them.
My replacement is now submitted and waits for approval. Meanwhile you can download the module and look at its features from its repository:
https://github.com/Moerill/fvtt-mars-5e
Manifest: https://raw.githubusercontent.com/Moerill/fvtt-mars-5e/master/module.json

(I'm currently going through all rolling related issues, pasting this as information and closing them)
