### ISSUE TITLE
Template Targeting Breaks when using a spell with a damage formula = 0

### ISSUE THREAD

**Issue by Ssezra** [Moerill/Mess#87]
MESS randomly stops auto targeting with templates? Upon F5 refresh MESS corrects itself and works but after a little bit it throws this error and stops selecting targets until another refresh.

181foundry.js:29953 Uncaught TypeError: Cannot read property 'equals' of undefined
    at User.updateTokenTargets (foundry.js:29953)
    at AbilityTemplate.i (modify-templates.js:177)
    at e.handlers.mm (eval at n (modify-templates.js:146), <anonymous>:17:12)
    at e.a.emit (index.js:202)
    at r.dispatchEvent (InteractionManager.js:1028)
    at r.processPointerMove (InteractionManager.js:1501)
    at pr.recursiveFindHit (TreeSearch.js:166)
    at pr.findHit (TreeSearch.js:191)
    at r.processInteractive (InteractionManager.js:1097)
    at r.onPointerMove (InteractionManager.js:1461)

After some testing it would appear that a spell placed with a damage formula = 0 breaks auto targeting. This can be reproduced every time. Example use case: Minor QoL with MESS.

Normally MESS and MQoL work fine together. Minor Qol seems to require a damage roll in order for spells to select targets and auto roll saving throws.  In order for MQoL to auto roll saving throws for spells which normally don't do damage (ie Faerie Fire) a damage formula = 0 would be required. (1d4 * 0)  When any spell template is placed by a spell with a damage formula = 0 MESS is unable to target tokens via the template. The above error displays in the F12 console. Any further spell templates are unable to target tokens until the web-page is refreshed.

**Comment by Moerill** [comment]
This won't be fixed, only update for mess that will be coming (regarding rolling issues) is removing them.
My replacement is now submitted and waits for approval. Meanwhile you can download the module and look at its features from its repository:
https://github.com/Moerill/fvtt-mars-5e
Manifest: https://raw.githubusercontent.com/Moerill/fvtt-mars-5e/master/module.json

(I'm currently going through all rolling related issues, pasting this as information and closing them)
