### ISSUE TITLE
Think about how to apply dmg

### ISSUE THREAD

**Issue by Moerill** [Moerill/Mess#9]
Context menu?
buttons?

**Comment by Moerill** [comment]
https://github.com/Moerill/Mess/issues/14#issue-620259897

**Comment by ultrakorne** [comment]
The right click context native menu I guess is fine / good to have. 

the 4 mini buttons that minorQOL has, I always forget which is which.

If 80% of the time we want damage, it can have 1 button for apply damage and to apply half/heal you still have to right click to get the context menu?

**Comment by Moerill** [comment]
Main questions  here for me are:
1. Context menu or buttons?
2. How to handle whether to use versatile or non versatile dmg?

**Comment by dlivitz** [comment]
minor_qol does buttons to the right of the rolled damage number - so you pick what to apply 

would be a usable placeholder while in pursuit of the perfect way to do it

**Comment by Lazytron** [comment]
MQoL version always seemed a bit busy to me, maybe a single button for "apply damage" with context menu for half/double/negative, and maybe a button below all of the boxes which aggregates all of the damage in the roll (nice to have for Magic Missile, weapons with multiple damage types, etc.)

**Comment by Moerill** [comment]
Solution for the moment:
2 type of context menus.
1 for every dmg rolled, applying only that dmg
![image](https://user-images.githubusercontent.com/26152015/85401293-127baa80-b55a-11ea-9b8f-3b1edc1ffbfe.png)

1 for all dmg rolls rolled, split into versatile and non versatile:
![image](https://user-images.githubusercontent.com/26152015/85401271-0abc0600-b55a-11ea-8f20-988ebab3af77.png)

I may revisit this decision at a later date.
