### ISSUE TITLE
 Blind and Self rolls not working when making rolls with Mess on

### ISSUE THREAD

**Issue by BleakForest** [Moerill/Mess#91]
I've discovered that by using Mess the blind and self roles don't work as intended when using certain functions, specifically skill/ability checks and saving throws made by clicking the corresponding sections in the character sheet. It's as if they were made as public rolls, everyone can see them.
 I made sure only Mess was on when using the blind/self roles feature to check if it was the mod responsible, and when no mods and even all the other mods were installed blind and self rolls worked properly. Using features/items/spells seemed to work fine, it appears to only affect the checks made in the attributes tab, being as mentioned before skill/ability checks and saving throws.

Browser for player's used, Chrome. Foundry Version, 0.6.5 5th Edition Version, 0.94 Mess Version used, 0.11.2

**Comment by Moerill** [comment]
This won't be fixed, only update for mess that will be coming (regarding rolling issues) is removing them.
My replacement is now submitted and waits for approval. Meanwhile you can download the module and look at its features from its repository:
https://github.com/Moerill/fvtt-mars-5e
Manifest: https://raw.githubusercontent.com/Moerill/fvtt-mars-5e/master/module.json

(I'm currently going through all rolling related issues, pasting this as information and closing them)
