### ISSUE TITLE
SUGGESTION: Make bonus damage only show up for attacks & saving throw action types

### ISSUE THREAD

**Issue by Pyroman2xxx** [Moerill/Mess#92]
Make bonus damage only show up for attacks & saving throw action types.

This way bonus damage is not shown on the card when using a healing or utility ability.

**Comment by Moerill** [comment]
This won't be fixed, only update for mess that will be coming (regarding rolling issues) is removing them.
My replacement is now submitted and waits for approval. Meanwhile you can download the module and look at its features from its repository:
https://github.com/Moerill/fvtt-mars-5e
Manifest: https://raw.githubusercontent.com/Moerill/fvtt-mars-5e/master/module.json

(I'm currently going through all rolling related issues, pasting this as information and closing them)
