### ISSUE TITLE
Suggestion: Add option to remove first attack card after initiating an attack

### ISSUE THREAD

**Issue by PupperooX** [Moerill/Mess#96]
The module is great, except my chat log keeps getting gummed up with attack cards before the actual roll. It'd be good to be able to disable this as it's meaning with a few quick attack from a couple of monsters and the log is clogged up with double the messages.

![image](https://user-images.githubusercontent.com/67825695/89108193-5d78bf80-d42e-11ea-86be-48c248e5c522.png)

**Comment by Puddinglord** [comment]
Based on this on the player's side when I select an attack they are able to see the weapon/attack that is going to hit them (which is fine) but they can also see the information below it which means they can see the hit die for the weapon and the modifier based on the attack of said weapon/attack.

Would it be possible to have an option to remove the first card that's displayed to the players and only display the GM one you created?

**Comment by Moerill** [comment]
This won't be fixed, only update for mess that will be coming (regarding rolling issues) is removing them.
My replacement is now submitted and waits for approval. Meanwhile you can download the module and look at its features from its repository:
https://github.com/Moerill/fvtt-mars-5e
Manifest: https://raw.githubusercontent.com/Moerill/fvtt-mars-5e/master/module.json

(I'm currently going through all rolling related issues, pasting this as information and closing them)
